class EPPPConfig:
    """EPPP Exam Configuration Constants"""

    # EXAM_DURATION_SECONDS = 15
    TOTAL_QUESTIONS = 225
    EXAM_DURATION_SECONDS = 15300  # 4h 15min
    PASSING_SCORE = 500
    SUPERVISED_PASSING_SCORE = 450

    # Score scale
    MIN_SCALED_SCORE = 200
    MAX_SCALED_SCORE = 800
