/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsIndexRouteImport } from './routes/results/index'
import { Route as ExamIndexRouteImport } from './routes/exam/index'
import { Route as ResultsSessionIdRouteImport } from './routes/results/$sessionId'
import { Route as ExamSessionIdRouteImport } from './routes/exam/$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIndexRoute = ResultsIndexRouteImport.update({
  id: '/results/',
  path: '/results/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamIndexRoute = ExamIndexRouteImport.update({
  id: '/exam/',
  path: '/exam/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsSessionIdRoute = ResultsSessionIdRouteImport.update({
  id: '/results/$sessionId',
  path: '/results/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamSessionIdRoute = ExamSessionIdRouteImport.update({
  id: '/exam/$sessionId',
  path: '/exam/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exam/$sessionId': typeof ExamSessionIdRoute
  '/results/$sessionId': typeof ResultsSessionIdRoute
  '/exam': typeof ExamIndexRoute
  '/results': typeof ResultsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exam/$sessionId': typeof ExamSessionIdRoute
  '/results/$sessionId': typeof ResultsSessionIdRoute
  '/exam': typeof ExamIndexRoute
  '/results': typeof ResultsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exam/$sessionId': typeof ExamSessionIdRoute
  '/results/$sessionId': typeof ResultsSessionIdRoute
  '/exam/': typeof ExamIndexRoute
  '/results/': typeof ResultsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exam/$sessionId'
    | '/results/$sessionId'
    | '/exam'
    | '/results'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/exam/$sessionId' | '/results/$sessionId' | '/exam' | '/results'
  id:
    | '__root__'
    | '/'
    | '/exam/$sessionId'
    | '/results/$sessionId'
    | '/exam/'
    | '/results/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamSessionIdRoute: typeof ExamSessionIdRoute
  ResultsSessionIdRoute: typeof ResultsSessionIdRoute
  ExamIndexRoute: typeof ExamIndexRoute
  ResultsIndexRoute: typeof ResultsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/': {
      id: '/results/'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/': {
      id: '/exam/'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$sessionId': {
      id: '/results/$sessionId'
      path: '/results/$sessionId'
      fullPath: '/results/$sessionId'
      preLoaderRoute: typeof ResultsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$sessionId': {
      id: '/exam/$sessionId'
      path: '/exam/$sessionId'
      fullPath: '/exam/$sessionId'
      preLoaderRoute: typeof ExamSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamSessionIdRoute: ExamSessionIdRoute,
  ResultsSessionIdRoute: ResultsSessionIdRoute,
  ExamIndexRoute: ExamIndexRoute,
  ResultsIndexRoute: ResultsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
