/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestSessionIdRouteImport } from './routes/test.$sessionId'
import { Route as ExamSessionIdRouteImport } from './routes/exam.$sessionId'

const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestSessionIdRoute = TestSessionIdRouteImport.update({
  id: '/test/$sessionId',
  path: '/test/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamSessionIdRoute = ExamSessionIdRouteImport.update({
  id: '/exam/$sessionId',
  path: '/exam/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/results': typeof ResultsRoute
  '/exam/$sessionId': typeof ExamSessionIdRoute
  '/test/$sessionId': typeof TestSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/results': typeof ResultsRoute
  '/exam/$sessionId': typeof ExamSessionIdRoute
  '/test/$sessionId': typeof TestSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/results': typeof ResultsRoute
  '/exam/$sessionId': typeof ExamSessionIdRoute
  '/test/$sessionId': typeof TestSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/results' | '/exam/$sessionId' | '/test/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/results' | '/exam/$sessionId' | '/test/$sessionId'
  id: '__root__' | '/' | '/results' | '/exam/$sessionId' | '/test/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResultsRoute: typeof ResultsRoute
  ExamSessionIdRoute: typeof ExamSessionIdRoute
  TestSessionIdRoute: typeof TestSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$sessionId': {
      id: '/test/$sessionId'
      path: '/test/$sessionId'
      fullPath: '/test/$sessionId'
      preLoaderRoute: typeof TestSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$sessionId': {
      id: '/exam/$sessionId'
      path: '/exam/$sessionId'
      fullPath: '/exam/$sessionId'
      preLoaderRoute: typeof ExamSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResultsRoute: ResultsRoute,
  ExamSessionIdRoute: ExamSessionIdRoute,
  TestSessionIdRoute: TestSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
